// Read-only release gate: generated bytes, source baseline and pinned upstream.
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { inventory, sha } from './inventory.mjs';
const here = new URL('./', import.meta.url);
const json = async name => JSON.parse(await readFile(new URL(name, here), 'utf8'));
export async function verifyRelease() {
  const baseline = await json('results/original-inventory.json');
  const current = await inventory();
  assert.equal(current.records.length, 1151);
  assert.deepEqual(current, baseline, 'never regenerate the original baseline to hide changes');
  const manifest = await json('pwa-dist/pwa-build.json');
  assert.equal(manifest.originalDigest, current.originalDigest);
  assert.equal(manifest.originalCount, current.records.length);
  assert.equal(manifest.iPhoneTested, false);
  const template = await readFile(new URL('sw-template.js', here), 'utf8');
  assert.equal(manifest.release, sha(JSON.stringify(manifest.assets) + template).slice(0, 20));
  const expectedSW = template.replace('__RELEASE__', JSON.stringify(manifest.release))
    .replace('__ASSETS__', JSON.stringify(manifest.assets, null, 2));
  assert.equal(await readFile(new URL('pwa-dist/sw.js', here), 'utf8'), expectedSW);
  const expectedNames = ['index.html', 'browser.js', 'engine-worker.js', 'eraJS-LICENSE.txt', 'build.json',
    'local-game.bin', 'manifest.webmanifest', 'icon-180.png', 'icon-192.png', 'icon-512.png'];
  assert.deepEqual(Object.keys(manifest.assets).sort(), expectedNames.sort());
  assert.deepEqual((await readdir(new URL('pwa-dist/', here))).sort(), [...expectedNames, 'sw.js', 'pwa-build.json'].sort());
  const artifacts = {}; let bytes = 0;
  for (const name of [...expectedNames, 'sw.js', 'pwa-build.json']) {
    const data = await readFile(new URL('pwa-dist/' + name, here));
    artifacts['pwa-dist/' + name] = sha(data);
    if (name !== 'pwa-build.json') bytes += data.length;
    if (name in manifest.assets) assert.equal(sha(data), manifest.assets[name], name);
  }
  assert.equal(bytes, manifest.bytes);
  for (const name of ['browser.js', 'engine-worker.js', 'eraJS-LICENSE.txt', 'build.json', 'engine.mjs', 'engine-legacy.mjs', 'engine-save-only.mjs', 'index.html']) {
    const data = await readFile(new URL('dist/' + name, here));
    artifacts['dist/' + name] = sha(data);
    if (['browser.js', 'engine-worker.js', 'eraJS-LICENSE.txt', 'build.json'].includes(name)) {
      assert.equal(sha(data), manifest.assets[name], 'dist/PWA mismatch: ' + name);
    }
  }
  const html = (await readFile(new URL('dist/index.html', here), 'utf8')).replace('data-pwa="false"', 'data-pwa="true"')
    .replace('<!-- PWA_LINKS -->', '<link rel="manifest" href="manifest.webmanifest">\n<link rel="apple-touch-icon" href="icon-180.png">');
  assert.equal(sha(html), manifest.assets['index.html']);
  const build = await json('pwa-dist/build.json');
  assert.equal(build.commit, 'fb487bceacd899a033db017ff0dff5bb3878d4a5');
  assert.match(build.saveOptimization, /^era-save-memory-v1/);
  assert.match(build.runtimeOptimization, /^era-deferred-local-v1/);
  assert.equal(build.sha256, manifest.assets['browser.js']);
  const engine = fileURLToPath(new URL('../../.my_agent_remote/undercrow__eraJS/', here));
  const git = (...args) => execFileSync('git', ['-C', engine, ...args], { encoding: 'utf8' }).trim();
  assert.equal(git('rev-parse', 'HEAD'), build.commit);
  assert.equal(git('status', '--porcelain', '--untracked-files=no'), '', 'upstream tracked files changed');
  const sources = {};
  for (const name of (await readdir(here)).sort()) {
    if (/\.(mjs|html|json)$/.test(name) || name === 'sw-template.js') sources[name] = sha(await readFile(new URL(name, here)));
  }
  return { release: manifest.release, originalCount: current.records.length, originalDigest: current.originalDigest,
    upstreamCommit: build.commit, upstreamTrackedClean: true, bytes, artifacts, sources, actualIPhone: false };
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const result = await verifyRelease();
  console.log(JSON.stringify({ passed: true, ...result }, null, 2));
}
